"""capability_requests, kill_state, kill audit event types

Revision ID: 80951989de42
Revises: d405f45ef0a6
Create Date: 2026-07-27 08:11:51.630013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80951989de42'
down_revision: Union[str, Sequence[str], None] = 'd405f45ef0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engaged', sa.Boolean(), nullable=False),
    sa.Column('engaged_at', sa.DateTime(), nullable=True),
    sa.Column('engaged_by', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('released_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('flow_id', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('pending', 'granted', 'denied', 'expired', name='requeststatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('denied_reason', sa.String(length=512), nullable=True),
    sa.Column('grant_id', sa.String(length=32), nullable=True),
    sa.Column('token_plaintext', sa.String(length=128), nullable=True),
    sa.Column('token_claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['capability_grants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capability_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_requests_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_requests_status'), ['status'], unique=False)

    # HAND-ADDED (Alembic does not diff CHECK constraints): widen the
    # audit event enum with the two kill-switch transition types. Batch
    # mode rebuilds the table so the CHECK actually changes on SQLite.
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column(
            'event_type',
            existing_type=sa.Enum(
                'request', 'grant', 'denial', 'use', 'revocation',
                name='auditeventtype', native_enum=False,
                create_constraint=True, length=16),
            type_=sa.Enum(
                'request', 'grant', 'denial', 'use', 'revocation',
                'kill_engaged', 'kill_released',
                name='auditeventtype', native_enum=False,
                create_constraint=True, length=16),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_requests_status'))
        batch_op.drop_index(batch_op.f('ix_capability_requests_flow_id'))

    op.drop_table('capability_requests')
    op.drop_table('kill_state')
    # HAND-ADDED mirror of the enum widening. NOTE: rows already using
    # the kill_* values would violate the narrowed CHECK — acceptable
    # for a dev-time downgrade, would need a data migration in prod.
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column(
            'event_type',
            existing_type=sa.Enum(
                'request', 'grant', 'denial', 'use', 'revocation',
                'kill_engaged', 'kill_released',
                name='auditeventtype', native_enum=False,
                create_constraint=True, length=16),
            type_=sa.Enum(
                'request', 'grant', 'denial', 'use', 'revocation',
                name='auditeventtype', native_enum=False,
                create_constraint=True, length=16),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
