"""principals, profile grants, audit attribution (7.2.1, ADR-005)

- `principals`: the identity ledger — WHO a person is (email + TOFU-
  pinned IdP subject). Authorization (groups, entitlements) is NOT
  here: it lives in the policy store the console edits (ADR-005 D5).
- flows / capability_requests / capability_grants gain a nullable
  `principal_id` — ADR-004 debt 1 (attribution before rows exist).
  The debt's "two users' flow-1 collide" half is retired WITHOUT
  re-keying flows: person-flow ids are gateway-minted (7.3), unique
  by construction; client-chosen ids only ever existed in the
  single-tenant mTLS domain.
- capability_grants: `flow_id` NULLABLE (profile grants hang on the
  person; the check path denies flow-less grants until 7.3's door
  exists) + `profile` / `tools_json` (SNAPSHOT at mint — later policy
  edits must not widen live grants) / `granted_via` (admin | confirm |
  approve — the ADR-005 carve, visible per row; server_default 'admin'
  backfills existing rows, hand-added: autogen emits NOT NULL with no
  default, which fails on any table with rows).
- audit_events: `principal` / `resource` / `policy_version` — the
  who / on-what / under-which-policy columns ADR-005 D3 requires.
- AuditEventType enum deliberately UNTOUCHED — no CHECK rebuild this
  time (revoke reuses REVOCATION with details.cause); the hand-widened
  CHECK trap of the last three migrations does not apply.
- FKs are NAMED (hand-edit): autogen emitted create/drop_constraint
  with name=None, and drop_constraint(None) raises at downgrade.

Revision ID: 86c82f996509
Revises: cdf028306ccc
Create Date: 2026-08-02 09:16:44.377835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c82f996509'
down_revision: Union[str, Sequence[str], None] = 'cdf028306ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('idp_sub', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idp_sub')
    )
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_principals_email'), ['email'], unique=True)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('resource', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('policy_version', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_events_principal'), ['principal'], unique=False)

    with op.batch_alter_table('capability_grants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('profile', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tools_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('granted_via', sa.String(length=16),
                                      nullable=False, server_default='admin'))
        batch_op.alter_column('flow_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_capability_grants_principal_id'), ['principal_id'], unique=False)
        batch_op.create_foreign_key('fk_capability_grants_principal', 'principals', ['principal_id'], ['id'])

    with op.batch_alter_table('capability_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('profile', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('window_minutes', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_capability_requests_principal_id'), ['principal_id'], unique=False)
        batch_op.create_foreign_key('fk_capability_requests_principal', 'principals', ['principal_id'], ['id'])

    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_flows_principal_id'), ['principal_id'], unique=False)
        batch_op.create_foreign_key('fk_flows_principal', 'principals', ['principal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_constraint('fk_flows_principal', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_flows_principal_id'))
        batch_op.drop_column('principal_id')

    with op.batch_alter_table('capability_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_capability_requests_principal', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_capability_requests_principal_id'))
        batch_op.drop_column('window_minutes')
        batch_op.drop_column('profile')
        batch_op.drop_column('principal_id')

    with op.batch_alter_table('capability_grants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_capability_grants_principal', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_capability_grants_principal_id'))
        batch_op.alter_column('flow_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('granted_via')
        batch_op.drop_column('tools_json')
        batch_op.drop_column('profile')
        batch_op.drop_column('principal_id')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_principal'))
        batch_op.drop_column('policy_version')
        batch_op.drop_column('resource')
        batch_op.drop_column('principal')

    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_principals_email'))

    op.drop_table('principals')
    # ### end Alembic commands ###
