"""human auth: operators, credentials, sessions, enrollment, challenges

Revision ID: cdf028306ccc
Revises: e0b009f26f01
Create Date: 2026-07-27 12:48:43.147319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf028306ccc'
down_revision: Union[str, Sequence[str], None] = 'e0b009f26f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_OLD = ('request', 'grant', 'denial', 'use', 'revocation',
        'kill_engaged', 'kill_released', 'claim')
_NEW = _OLD + ('auth_success', 'auth_failure', 'credential_added')


def _enum(values):
    return sa.Enum(*values, name='auditeventtype', native_enum=False,
                   create_constraint=True, length=16)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_codes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_codes_code_hash'), ['code_hash'], unique=True)

    op.create_table('operators',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('webauthn_challenges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('challenge', sa.LargeBinary(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('enrollment_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('console_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('console_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_console_sessions_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_console_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('webauthn_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('credential_id', sa.String(length=512), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webauthn_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webauthn_credentials_credential_id'), ['credential_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_webauthn_credentials_operator_id'), ['operator_id'], unique=False)

    # ### end Alembic commands ###

    # HAND-ADDED (Alembic still does not diff CHECK constraints — third
    # time): widen the audit enum with the human-auth transitions, or the
    # model would emit values the old constraint rejects at runtime.
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('event_type', existing_type=_enum(_OLD),
                              type_=_enum(_NEW), existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # HAND-ADDED mirror. Existing auth_* rows would violate the narrowed
    # CHECK — fine for a dev downgrade, needs a data migration in prod.
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('event_type', existing_type=_enum(_NEW),
                              type_=_enum(_OLD), existing_nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webauthn_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webauthn_credentials_operator_id'))
        batch_op.drop_index(batch_op.f('ix_webauthn_credentials_credential_id'))

    op.drop_table('webauthn_credentials')
    with op.batch_alter_table('console_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_console_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_console_sessions_operator_id'))

    op.drop_table('console_sessions')
    op.drop_table('webauthn_challenges')
    op.drop_table('operators')
    with op.batch_alter_table('enrollment_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_codes_code_hash'))

    op.drop_table('enrollment_codes')
    # ### end Alembic commands ###
