"""core tables: flows, capability_grants, audit_events

Revision ID: d405f45ef0a6
Revises: 
Create Date: 2026-07-27 08:00:32.303753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd405f45ef0a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('request', 'grant', 'denial', 'use', 'revocation', name='auditeventtype', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('flow_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=128), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_ts'), ['ts'], unique=False)

    op.create_table('flows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_grants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('flow_id', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by', sa.String(length=128), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('capability_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_grants_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_grants_flow_id'), ['flow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_grants_flow_id'))
        batch_op.drop_index(batch_op.f('ix_capability_grants_expires_at'))

    op.drop_table('capability_grants')
    op.drop_table('flows')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_events_flow_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
