"""claim_nonce_hash + claim audit event type

Revision ID: e0b009f26f01
Revises: 80951989de42
Create Date: 2026-07-27 10:37:49.225010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b009f26f01'
down_revision: Union[str, Sequence[str], None] = '80951989de42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_OLD = ('request', 'grant', 'denial', 'use', 'revocation',
        'kill_engaged', 'kill_released')
_NEW = _OLD + ('claim',)


def _enum(values):
    return sa.Enum(*values, name='auditeventtype', native_enum=False,
                   create_constraint=True, length=16)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_nonce_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_capability_requests_claim_nonce_hash'), ['claim_nonce_hash'], unique=False)

    # ### end Alembic commands ###

    # HAND-ADDED, same trap as 80951989de42: Alembic does not diff CHECK
    # constraints, so the new 'claim' event type would be rejected at
    # runtime by the old constraint while the model happily emitted it.
    # Batch mode rebuilds the table so the CHECK actually changes.
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('event_type', existing_type=_enum(_OLD),
                              type_=_enum(_NEW), existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # HAND-ADDED mirror. NOTE: existing 'claim' rows would violate the
    # narrowed CHECK — fine for a dev-time downgrade, would need a data
    # migration in prod (same caveat as 80951989de42).
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('event_type', existing_type=_enum(_NEW),
                              type_=_enum(_OLD), existing_nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_requests_claim_nonce_hash'))
        batch_op.drop_column('claim_nonce_hash')

    # ### end Alembic commands ###
