"""audit hash chain

Revision ID: e0d96023a23d
Revises: f41d02a9c8b3
Create Date: 2026-08-03 20:09:12.821959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d96023a23d'
down_revision: Union[str, Sequence[str], None] = 'f41d02a9c8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('row_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_events_row_hash'), ['row_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_row_hash'))
        batch_op.drop_column('row_hash')
        batch_op.drop_column('prev_hash')

    # ### end Alembic commands ###
