argo-cd:
    configs:
        repositories:
            homelab:
                url: git@github.com:itdan-com/homelab.git
                name: homelab
                type: git
                sshPrivateKey: ENC[AES256_GCM,data:aVW0Rg/gFBY4XlYnSeJwwVEKEzAJx57CTjzgUqAccx+wg7EUO15dNt+tZiIN0Dyd5qM/Ef5cDWx76nGSQ9rZfPXDibtGjrmVh7RS7db9awl3qLohtGZeaAkS3VP/hTc0yOckgEG7PbaHfh9nfa2Pkb+W/puZO2HAGYBwO7vjHpPxGa3yY6mdvK+M2ObVDk0sGv6VBr0d2XOMBImpN0/Q2jNaGRSNPeSrV6J2gQVt4AfEl38ALbulxvJG0Oplh6oYh9EQxR+Mff37KfOT4iNqW3S3l+xQR4O8kC5WSf9KdjD0NQ7PdWVF7FlG3YB6uWAfDwOTFGrsUNaNvDR2YwihwHPqhKTZGftHobpQuETpWhyAriHxJ75PNTDpiVxEUhYSVLokRnhNWHPQUaflh1mIUEEw6dLmex6h1LKH/zJNMr7abE4lv7b41rptw/4+GJL1qvy6pF+PQmP/ldJehB1WhpqwBeOjzrQSMvT15Ens23tcr20uswiQRHoo18UQWfozqJUrdBGZjJHXRiN99pojnjXmFcnavSIU9fSIq51QKROcGKo=,iv:mF5Wx92v5Lc5Gx02VSNoeDtnUsTEChPo3GFL8lxl49s=,tag:Gn32ZUk4dLnBA3/KqaC4bQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdTEvczFmZmdweFQ5Sm1H
            WEFZelByaWZsRjEyZFFheEY0WW1PMzY0T1VVCkRMZjBNV0YrU1JHOXpNOTR0aTUz
            NE92Q2N2bHNnRHhNM0pBQmZES0ZFeHcKLS0tIDBFOHpIaW1oOXVlVlk4TnBPSU5H
            ZTJXdHZLNWVzaFMxSTNVeVJpOXJrYlEKPXL90EhPsL7I8W16hlIFXllDIDExFBEa
            e17x7w+Ga9RXfZnLNVd4tw6brqN+WRd9cooaKuyDLzhDnPcjalxkgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13dr952jeym9vk9kr9fglgpj6n3rxznpuvtnr8hmvdsfn2w5r5aeqdwlhpf
    encrypted_regex: ^(data|stringData|password|.*[Pp]assword|.*[Tt]oken|.*[Kk]ey|.*[Ss]ecret)$
    lastmodified: "2026-07-25T23:22:39Z"
    mac: ENC[AES256_GCM,data:jFsd4N8CmCuRPM5vw2G2DsqmC+n8U7Nt7FQ22C52ZPjdCDltj41W/FUjiLLj+M+Z2zqZMIb6K1tqntSItVk6KD0j14UtsN899Xj47g2uurND6mdQ44uctCOz2jGaWNNse9M7dknueWsLFSfVV1vQuuLkDib/dW1IA5sP4uXri7Y=,iv:JXthAe9/Fqj72QxMal3r/lYLVra87wg6WwekMAf/wPI=,tag:ep8jG3x/gwwdIps2qNHUZA==,type:str]
    version: 3.13.1
