argo-cd:
    configs:
        repositories:
            homelab:
                url: git@github.com:itdan-com/homelab.git
                name: homelab
                type: git
                sshPrivateKey: ENC[AES256_GCM,data:aVW0Rg/gFBY4XlYnSeJwwVEKEzAJx57CTjzgUqAccx+wg7EUO15dNt+tZiIN0Dyd5qM/Ef5cDWx76nGSQ9rZfPXDibtGjrmVh7RS7db9awl3qLohtGZeaAkS3VP/hTc0yOckgEG7PbaHfh9nfa2Pkb+W/puZO2HAGYBwO7vjHpPxGa3yY6mdvK+M2ObVDk0sGv6VBr0d2XOMBImpN0/Q2jNaGRSNPeSrV6J2gQVt4AfEl38ALbulxvJG0Oplh6oYh9EQxR+Mff37KfOT4iNqW3S3l+xQR4O8kC5WSf9KdjD0NQ7PdWVF7FlG3YB6uWAfDwOTFGrsUNaNvDR2YwihwHPqhKTZGftHobpQuETpWhyAriHxJ75PNTDpiVxEUhYSVLokRnhNWHPQUaflh1mIUEEw6dLmex6h1LKH/zJNMr7abE4lv7b41rptw/4+GJL1qvy6pF+PQmP/ldJehB1WhpqwBeOjzrQSMvT15Ens23tcr20uswiQRHoo18UQWfozqJUrdBGZjJHXRiN99pojnjXmFcnavSIU9fSIq51QKROcGKo=,iv:mF5Wx92v5Lc5Gx02VSNoeDtnUsTEChPo3GFL8lxl49s=,tag:Gn32ZUk4dLnBA3/KqaC4bQ==,type:str]
        secret:
            extra:
                oidc.authentik.clientSecret: ENC[AES256_GCM,data:gWHYCt4zyz14r7VRYYWEBfbPYewyAIC99TqTyMfsG/99UQ4w89D9zGWyJsGsSBQtRUwoz3odTgyiemm3M5VOzg==,iv:aEiX4+526+rCAFz+Gw9y9p/w9Bd/Q61jl6HZBqGGQCE=,tag:VN7PBCf3y0bkhK09R1/7sQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdTEvczFmZmdweFQ5Sm1H
            WEFZelByaWZsRjEyZFFheEY0WW1PMzY0T1VVCkRMZjBNV0YrU1JHOXpNOTR0aTUz
            NE92Q2N2bHNnRHhNM0pBQmZES0ZFeHcKLS0tIDBFOHpIaW1oOXVlVlk4TnBPSU5H
            ZTJXdHZLNWVzaFMxSTNVeVJpOXJrYlEKPXL90EhPsL7I8W16hlIFXllDIDExFBEa
            e17x7w+Ga9RXfZnLNVd4tw6brqN+WRd9cooaKuyDLzhDnPcjalxkgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13dr952jeym9vk9kr9fglgpj6n3rxznpuvtnr8hmvdsfn2w5r5aeqdwlhpf
    encrypted_regex: ^(data|stringData|password|.*[Pp]assword|.*[Tt]oken|.*[Kk]ey|.*[Ss]ecret)$
    lastmodified: "2026-07-27T04:38:36Z"
    mac: ENC[AES256_GCM,data:Zf0vieV3zK0wf653wnxPta/F+tJb9Sr3tHY6dIrLrqtwF6djfEreT8E9rMSWilm6oBmkyBSg+y4KKl8nqBxQETK9jt1ei2gUccq/l0vhFj+/U25Fhc5e+EAo1lkPD0vK/CAmbCrjTkKj0WtwcLP+NTJJHuEBzxPtNxKycoVUh8U=,iv:GEwCim5may6jBvx5NQgqbbUQsbSNfIKJ8X7b42hDEqg=,tag:zfPlcT7DR7xok7strVTgjQ==,type:str]
    version: 3.13.1
