{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.entrypoint }}
  routes:
    - match: Host(`{{ include "catalog.ingressHost" . }}`)
      kind: Rule
      services:
        - name: {{ include "catalog.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
