#!/usr/bin/env bash
# sentinel/scripts/install-systemd.sh — deploy Sentinel as a service.
#
# ONE install path for every Linux host (ADR-004 construction rule).
# Cloud-init on a DigitalOcean droplet calls this same script; nothing
# below knows or cares that today's host happens to be WSL2. The single
# lab-specific fact — which address the cluster reaches the broker on —
# is DETECTED here and written to /etc/sentinel/sentinel.env, so the
# unit files stay environment-agnostic. In cloud you pass it in:
#
#   SENTINEL_BROKER_BIND=10.1.2.3 sudo -E ./scripts/install-systemd.sh
#
# Idempotent. Re-run it after `git pull` — that IS the deploy step, and
# it is deliberate rather than a git checkout being hot-swapped under a
# running service.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_DIR="${SENTINEL_APP_DIR:-/opt/sentinel}"
ETC_DIR="${SENTINEL_ETC_DIR:-/etc/sentinel}"
CERT_DIR="${SENTINEL_CERT_DIR:-$ETC_DIR/certs}"
STATE_DIR="${SENTINEL_STATE_DIR:-/var/lib/sentinel}"
SVC_USER="${SENTINEL_USER:-sentinel}"
ADMIN_BIND="${SENTINEL_ADMIN_BIND:-127.0.0.1}"
ADMIN_PORT="${SENTINEL_ADMIN_PORT:-8400}"
BROKER_PORT="${SENTINEL_BROKER_PORT:-8401}"
RP_ID="${SENTINEL_RP_ID:-localhost}"
K3D_NETWORK="${K3D_NETWORK:-k3d-devlab}"

[[ $EUID -eq 0 ]] || { echo "!! run with sudo" >&2; exit 1; }

# The broker's address: given, or detected from the local container
# network. Detection lives HERE and only here.
BROKER_BIND="${SENTINEL_BROKER_BIND:-$(docker network inspect "$K3D_NETWORK" \
  --format '{{(index .IPAM.Config 0).Gateway}}' 2>/dev/null || true)}"
if [[ -z "$BROKER_BIND" ]]; then
  echo "!! could not detect a broker bind address." >&2
  echo "   Set SENTINEL_BROKER_BIND=<address pods reach this host on>." >&2
  exit 1
fi

echo "== service account: $SVC_USER"
id -u "$SVC_USER" >/dev/null 2>&1 || \
  useradd --system --home-dir "$STATE_DIR" --shell /usr/sbin/nologin "$SVC_USER"

echo "== deploying code to $APP_DIR (source: $REPO_DIR)"
install -d -o root -g root -m 0755 "$APP_DIR"
# The app only; never the developer's venv, dev database, or certs.
rm -rf "$APP_DIR/app" "$APP_DIR/migrations"
cp -r "$REPO_DIR/app" "$REPO_DIR/migrations" "$APP_DIR/"
install -m 0644 "$REPO_DIR/alembic.ini" "$REPO_DIR/requirements.txt" "$APP_DIR/"
find "$APP_DIR" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true

echo "== virtualenv"
[[ -x "$APP_DIR/.venv/bin/python" ]] || python3 -m venv "$APP_DIR/.venv"
"$APP_DIR/.venv/bin/pip" install --quiet --upgrade pip
"$APP_DIR/.venv/bin/pip" install --quiet -r "$APP_DIR/requirements.txt"

echo "== state + config directories"
install -d -o "$SVC_USER" -g "$SVC_USER" -m 0700 "$STATE_DIR"
install -d -o root -g root -m 0755 "$ETC_DIR"
install -d -o "$SVC_USER" -g "$SVC_USER" -m 0700 "$CERT_DIR"

# Certificates: reuse what already exists so the CA — and therefore the
# cluster's trust in it — survives a reinstall. Only mint when there is
# nothing to keep.
# Copy any cert this install is missing. Per-file, not all-or-nothing:
# the first version only copied when ca.crt was absent, so a re-install
# after minting a NEW leaf (the console cert) silently kept the old set
# and the service started against material that did not exist.
copied=0
for f in ca.crt ca.key broker.crt broker.key proxy-client.crt proxy-client.key \
         console.crt console.key; do
  if [[ ! -f "$CERT_DIR/$f" && -f "$REPO_DIR/certs/$f" ]]; then
    cp "$REPO_DIR/certs/$f" "$CERT_DIR/$f"; copied=$((copied + 1))
  fi
done
if (( copied )); then
  echo "== adopted $copied cert file(s) from the repo checkout (existing CA preserved)"
  chown -R "$SVC_USER:$SVC_USER" "$CERT_DIR"; chmod 0600 "$CERT_DIR"/*
fi
if [[ ! -f "$CERT_DIR/ca.crt" || ! -f "$CERT_DIR/console.crt" ]]; then
  echo "!! missing certificates (need ca.crt and console.crt)." >&2
  echo "   Run ./scripts/mint-certs.sh as the host user, then re-run this." >&2
  exit 1
fi

ENV_FILE="$ETC_DIR/sentinel.env"
if [[ -f "$ENV_FILE" ]]; then
  cp -a "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"   # never clobber config unbacked
  echo "== existing $ENV_FILE backed up"
fi
cat > "$ENV_FILE" <<EOF
# Generated by install-systemd.sh — the ONE place host-specific values
# live. The unit files read this and know nothing about the host.
SENTINEL_DB=$STATE_DIR/sentinel.db
SENTINEL_CERT_DIR=$CERT_DIR
SENTINEL_ADMIN_BIND=$ADMIN_BIND
SENTINEL_ADMIN_PORT=$ADMIN_PORT
SENTINEL_BROKER_BIND=$BROKER_BIND
SENTINEL_BROKER_PORT=$BROKER_PORT
SENTINEL_RP_ID=$RP_ID
SENTINEL_CONSOLE_ORIGIN=http://$RP_ID:$ADMIN_PORT
SENTINEL_CONSOLE_HOSTS=127.0.0.1,localhost
EOF
chmod 0640 "$ENV_FILE"; chown root:"$SVC_USER" "$ENV_FILE"

echo "== schema"
SENTINEL_DB="$STATE_DIR/sentinel.db" \
  runuser -u "$SVC_USER" -- "$APP_DIR/.venv/bin/alembic" \
  -c "$APP_DIR/alembic.ini" upgrade head

echo "== units"
install -m 0644 "$REPO_DIR/deploy/sentinel-admin.service" \
                "$REPO_DIR/deploy/sentinel-broker.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now sentinel-broker.service sentinel-admin.service
systemctl --no-pager --lines=0 status sentinel-broker.service sentinel-admin.service || true

# One command in, one URL out. The enrollment code is minted here and
# carried in the URL fragment — fragments are never sent to the server
# and never appear in access logs, so this is a link the operator can
# click rather than a code to copy between windows.
ENROLL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo operator)}"
CODE=$(runuser -u "$SVC_USER" -- env "SENTINEL_DB=$STATE_DIR/sentinel.db" \
  "$APP_DIR/.venv/bin/python" -c "
import sys; sys.path.insert(0, '$APP_DIR')
from app.auth import mint_enrollment_code
from app.db import SessionLocal
s = SessionLocal()
print(mint_enrollment_code(s, '$ENROLL_USER', 'first device'))")

cat <<EOF

  ============================================================
   Sentinel is running. Open this once and register a passkey:

     http://$RP_ID:$ADMIN_PORT/#enroll=$CODE

   That is the whole setup. The link expires in 10 minutes.
  ============================================================

  Add a second device later (do it — there is no recovery backdoor):
    sudo $REPO_DIR/scripts/enroll-operator.sh

  logs:  journalctl -u sentinel-admin -u sentinel-broker -f

EOF
